plugins {
    com.seeq.build.link.jvm.connector
}

description = "seeq-link-connector-iba-hd"
version = "100.0.${project.properties["seeqDaysVersion"]}.${project.properties["seeqSecondsVersion"]}" +
    "${project.properties["seeqVersionSuffix"]}"
connector.minSeeqLinkSdkVersion = "100.0.0.0" // Minimum Seeq Link SDK version required by this connector

dependencies {
    runtimeOnly("io.grpc:grpc-netty-shaded")
    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation("io.grpc:grpc-protobuf")
    implementation("io.grpc:grpc-kotlin-stub")
    testImplementation("com.asarkar.grpc:grpc-test:1.2.2")
    testImplementation("io.grpc:grpc-testing")
}

coverage {
    threshold.set(0.70)
    // Exclude code generated by protoc
    excludes.addAll(
        "ibahdapi/v1/**",
    )
}